spring:
  application:
    name: springbootapp
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-plateform: org.hibernate.dialect.H2Dialect
server:
  port: 8080

---
spring:
  profiles: dev
  application:
    name: springbootapp
server:
  port: 8080

---
spring:
  profiles: prod
  application:
    name: springbootapp
server:
  port: 9090
