spring:
  application:
    name: springbootapp
server:
  port: 8080

---
spring:
  profiles: dev
  application:
    name: springbootapp
server:
  port: 8080

---
spring:
  profiles: prod
  application:
    name: springbootapp
server:
  port: 9090
